### PR TITLE
README update

### PR DESCRIPTION
**Pull request by luzpaz**
Completed some task mentioned in #3

### CODE REVIEW

**Comment by luzpaz** [comment]
@oddtopus I can rebase this PR but I'm wondering if you have any issues with it? My thought process is to have the FC Workbench READMEs uniform to a certain extent. Care to share your thoughts on this?

**Comment by luzpaz** [comment]
@oddtopus ping

**Comment by luzpaz** [comment]
You can view it yourself here: https://github.com/luzpaz/flamingo/blob/c91aac53e577afb0894c0e1f8687ce5a74936a9c/README.md

image

**Comment by oddtopus** [comment]
That seems ok. I will only change the initial screenshot to a more recent one, also because those curve-fittings are not made by flamingo itself (but with OSE-piping-workbench, as you know).
Thank You also for the wiki: now that it's out of the sandbox I will add to it also description of new tools.
Just one thing: instead of pulling the README.md I will just include the raw file in my next commit, only to be sure not to create conflicts while fetching my local repository. (I'm still reading the manual of git!)

**Comment by oddtopus** [comment]
I have uploaded the screenshot on the wiki and would like to use the same in README.md
Will the following line work?
`screenshot1`

**Comment by luzpaz** [comment]
It should, AFAICT. Do you want me to test it or do you want to push the change to a branch and then view it on GH (before you merge) ?

**Comment by oddtopus** [comment]
I'll try it because sooner or later I must learn also this syntax.
can you advice a manual for that? what shall I google for?

**Comment by luzpaz** [comment]
@oddtopus 
:point_down: click that link that says: 'Styling with Markdown is supported' 
markdown

**Comment by easyw** [comment]
you may also have a look at 
https://pandao.github.io/editor.md/en.html
Open source online Markdown editor.

**Comment by oddtopus** [comment]
The README.md has been updated manually.
Thanks

**Pull request closed without merging**
